cask_args appdir: "/Applications"

# Taps

tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"


# Homebrew

brew "awscli"
brew "bfg"
brew "f3"
brew "howdoi"
brew "jq"
brew "mas"
brew "mutt" 
brew "nvm"
brew "p7zip"
#brew "ranger"
brew "raylib"
brew "rustup-init"
brew "shellcheck"
brew "stow"
brew "thefuck"
brew "unrar"
brew "wget"
brew "yarn"
brew "yarn-completion"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"


# Homebrew Casks

cask "adoptopenjdk8" unless system "/usr/libexec/java_home --failfast"
cask "amazon-music"
cask "anki"
cask "authy"
cask "calibre"
cask "discord"
cask "docker"
cask "dupeguru"
cask "font-meslo-for-powerline"
cask "franz"
cask "gitter"
cask "intellij-idea-ce"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "megasync"
cask "oversight"
cask "postman"
cask "skype"
cask "sonos"
cask "sonos-s1-controller"
cask "spectacle"
cask "steam"
cask "virtualbox"
cask "visual-studio-code"
cask "zerotier-one"


# App Store

mas "Ka-Block!", id: 1335413823
mas "Keynote", id: 409183694
mas "Master Password •••| — Get immune to loss.", id: 662763204
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "SomaFM Radio Player", id: 449155338
mas "WhatsApp Desktop", id: 1147396723
